FROM ubuntu:14.04

RUN apt-get update

RUN apt-get install -y tar wget autoconf libtool automake g++ make git bzip2 curl unzip zlib1g-dev patch

RUN apt-get install -y  vim

RUN apt-get update

RUN apt-get install -y software-properties-common python-software-properties

RUN add-apt-repository ppa:jonathonf/python-3.6

RUN apt-get update

RUN apt-get install -y python3.6

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.4 1

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2

# jonathonf/python3.6 has no ez_install and has broken pip in packages for ubuntu14.04
RUN curl https://bootstrap.pypa.io/ez_setup.py -o - | python3.6 && python3.6 -m easy_install pip

RUN pip3 install protobuf==3.0.0

RUN pip3 install kafka-python

CMD ["/bin/bash"]

